### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Wizz1337** [Nok1337s/Fake-Ethereum-Wallet-Miner#1]
hi, for this part of the code :
![image](https://user-images.githubusercontent.com/70026238/167712727-b4e5a412-ea3f-4d52-89c8-e1ab9e7289f8.png)

i recommand you to do like this 
```python
q = input("want start mining eth?(Y/N)").lower()
if q.startswith('y'):
    pass #also recommand to use a func
else:
    exit(1)
```

**Comment by Nok1337s** [comment]
Can we talk on discord? nok#1079

**Comment by Nok1337s** [comment]
> hi, for this part of the code :
> ![image](https://user-images.githubusercontent.com/70026238/167712727-b4e5a412-ea3f-4d52-89c8-e1ab9e7289f8.png)
> 
> i recommand you to do like this 
> ```python
> q = input("want start mining eth?(Y/N)").lower()
> if q.startswith('y'):
>     pass #also recommand to use a func
> else:
>     exit(1)
> ```


Can we talk on discord? nok#1079 ?

**Comment by Wizz1337** [comment]
sure
